import { Database } from "@/types";

export const database: Database[] = [
    { id: 1, title: "Database Item 1", course: "Course A" },
    { id: 2, title: "Database Item 2", course: "Course B" },
    { id: 3, title: "Database Item 3", course: "Course C" },
    { id: 4, title: "Database Item 4", course: "Course D" },
    { id: 5, title: "Database Item 5", course: "Course E" },
    { id: 6, title: "Database Item 6", course: "Course F" },
    { id: 7, title: "Database Item 7", course: "Course G" },
    { id: 8, title: "Database Item 8", course: "Course H" },
    { id: 9, title: "Database Item 9", course: "Course I" },
    { id: 10, title: "Database Item 10", course: "Course J" },
    { id: 11, title: "Database Item 11", course: "Course K" },
    { id: 12, title: "Database Item 12", course: "Course L" },
    { id: 13, title: "Database Item 13", course: "Course M" },
    { id: 14, title: "Database Item 14", course: "Course N" },
    { id: 15, title: "Database Item 15", course: "Course O" },
    { id: 16, title: "Database Item 16", course: "Course P" },
    { id: 17, title: "Database Item 17", course: "Course Q" },
    { id: 18, title: "Database Item 18", course: "Course R" },
    { id: 19, title: "Database Item 19", course: "Course S" },
    { id: 20, title: "Database Item 20", course: "Course T" },
    { id: 21, title: "Database Item 21", course: "Course U" },
    { id: 22, title: "Database Item 22", course: "Course V" },
    { id: 23, title: "Database Item 23", course: "Course W" },
    { id: 24, title: "Database Item 24", course: "Course X" },
    { id: 25, title: "Database Item 25", course: "Course Y" },
    { id: 26, title: "Database Item 26", course: "Course Z" },
    { id: 27, title: "Database Item 27", course: "Course AA" },
    { id: 28, title: "Database Item 28", course: "Course BB" },
    { id: 29, title: "Database Item 29", course: "Course CC" },
    { id: 30, title: "Database Item 30", course: "Course DD" },
];