/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ceNlNpY6h90
 */


export function ChatInput() {
  return (
    <div key="1" className="flex items-center p-6 bg-white rounded-md shadow">
      <input
        aria-label="Type message"
        className="flex-1 bg-transparent outline-none placeholder-gray-400 px-3"
        placeholder="Type message"
        type="text"
      />
      <button
        aria-label="Send message"
        className="ml-4 text-gray-500 hover:text-gray-700 focus:outline-none"
        type="submit"
      >
        <SendIcon className="w-6 h-6" />
      </button>
    </div>
  )
}


function SendIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
