/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Q0V8DZ06bd8
 */


export function DatabaseItem() {
  return (
    <div key="1" className="flex items-center justify-between px-6 py-4 bg-white rounded-lg shadow">
      <div className="flex flex-col">
        <span className="text-xs font-semibold text-green-600 uppercase">Lecture</span>
        <h2 className="text-2xl font-bold text-gray-700">Dental Proceedings 3</h2>
        <span className="text-sm text-gray-500">BIO 379, WN 2018</span>
      </div>
      <div className="flex items-center space-x-3">
        <ListIcon className="text-gray-400 w-5 h-5" />
        <XIcon className="text-gray-400 w-5 h-5" />
      </div>
    </div>
  )
}


function ListIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
