/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fEDAHaxOquY
 */


export function SelectedDataToggle() {
  return (
    <div className="flex items-center">
      <button
        aria-checked="true"
        className="relative inline-block w-12 h-6 bg-[#00a87e] rounded-full shadow-inner"
        role="switch"
      >
        <span className="absolute left-1 top-1 bg-white w-4 h-4 rounded-full shadow transition-transform transform translate-x-6" />
      </button>
      <span className="ml-3 text-lg font-medium">Selected</span>
    </div>
  )
}
