/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ugILYBo6NCc
 */
import type { Item } from "@/types/client";

export default function SourceViewer({...props}) {

  const source: Item = props.sourceViewer ;
  const setSourceViewer = props.setSourceViewer;
  const {
    name, author, course
  } = source;

  
  var icon = <VideoIcon className="w-6 h-6 text-green-600 mr-2" />

  // const type = 'video';
  // if (type === 'video') {
  //   const icon = <VideoIcon className="w-6 h-6 text-green-600 mr-2" />
  // }
  // else {
  //   const icon = <FileIcon className="w-6 h-6 text-green-600 mr-2" />
  // }

  console.log(source)

  return (
    <div className="flex flex-col bg-white p-4 h-full">
      <div className="flex items-center justify-between">
        <button onClick={() => {setSourceViewer(!source)}}>
          <ArrowLeftIcon className="w-5 h-5" />
        </button>
        <h1 className="text-xl font-semibold">{name}</h1>
        <span></span>
      </div>
      <div className="mt-4 h-full">
        <iframe className="flex w-full h-1/2 rounded-lg" src="https://umich.instructure.com/courses/462614/files/23404364?module_item_id=2073567" allowFullScreen></iframe>
        <div className="mt-4 p-4 h-1/2 shadow rounded-lg overflow-y-auto">
          <h2 className="text-lg font-semibold flex items-center">
            {icon}
            Source Guide
            <button className="ml-auto">
              <ChevronDownIcon className="w-4 h-4" />
            </button>
          </h2>
          <div className="mt-4">
            <h3 className="text-med font-semibold">{author}</h3>
            <p className="mt-2 italic">{course}</p>
          </div>
        </div>
      </div>
    </div>
  )
}


function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}

function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 8-6 4 6 4V8Z" />
      <rect width="14" height="12" x="2" y="6" rx="2" ry="2" />
    </svg>
  )
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}
